### ISSUE TITLE
Lexer (lex.c) requires maintenance. 

### ISSUE THREAD

**Issue by LandonPowell** [kjensenxz/lol-qwop-lang#3]
Within lex.c, starting at line 34 - https://github.com/kjensenxz/lol-qwop-lang/blob/master/c/lex.c#L34

The code needs to be heavily refactored. It'd be better done with a switch, but your repeated use of different lols, such as "lol., lol?, lol!" instead of recognizing "lol" as a token and "!" as a token is an issue in and of itself. The recapitulation that is #L34 - #L53 is duress inducing and isn't a healthy environment for developing on top of. 

>` Also, hey you're still alive? `

**Comment by tudurom** [comment]
It's not possible to write a `switch`-`case` in C. Also, why recognize `lol` as a token and `!` as a token when the real token is `lol!`?

**Comment by LandonPowell** [comment]
>It's not possible to write a switch-case in C
http://www.cprogramming.com/tutorial/lesson5.html 
http://www.tutorialspoint.com/cprogramming/switch_statement_in_c.htm  
https://en.wikipedia.org/wiki/Switch_statement 

Yes it is. Please delete your comment, Tudorom. 

The real token is `lol!` because you've coded it that way. My point is to not make it the real token.

Did I just get trolled or something?

**Comment by tudurom** [comment]
Excuse my mistake, I meant it's not possible to write a switch-case for strings in C. derp.

>The real token is `lol!` because it was coded it that way. My point is to make it not the real token. 

It's the spec's fault that `lol` and `qwop` are repetitive, the program just finds tokens. It's simple, efficient, the code is short and concise and it works. I see no point in refactoring that part of the code.

**Comment by LandonPowell** [comment]
It is not efficient, nor is it simple. You're closing this issue because it involves you being embarrassed about saying something dumb. That's damn near the least professional thing I've ever seen. 

The program doesn't find tokens. It's a lexer. It chooses what is and isn't a token to make future things easier, which it isn't doing. You could arbitrarily rip the string in half at any given point and it'd technically be a valid token if you felt like it, but it isn't efficient nor is it good code. With some nested conditionals, the code would be much better.

**Comment by Randl** [comment]
I believe this code would be more efficient:

```c
/* Returns the next token */
int get_tok(FILE *file) {
    int last_char;
    int IdentifierStr_len;

    /* eat whitespace */
    do {
        last_char = fgetc(file);
    } while (isspace(last_char));

    if (is_valid(last_char)) {
        /* read token */
        IdentifierStr_len = 0;
        do {
            IdentifierStr[IdentifierStr_len] = last_char;
            IdentifierStr_len++;
        } while (is_valid(last_char = fgetc(file)));
        IdentifierStr[IdentifierStr_len] = '\0';

        /* get token type */
		if (strncmp(IdentifierStr, "lol", 3) == 0) {  //string starting with "lol"
			if (IdentifierStr_len == 3)
				return TOK_MV_RIGHT;
			
			if (IdentifierStr_len == 4)
				switch (IdentifierStr[3]) {
					case '.': return TOK_MV_LEFT;
					case '!': return TOK_INCR;
					case '?': return TOK_DECR;
					default: return TOK_COMMENT;
				}
				
			if (strncmp(IdentifierStr, "lol-qwop", 8) == 0) {
				if (IdentifierStr_len == 8)
					return TOK_PRINT;
				if (IdentifierStr_len == 9 && IdentifierStr[8] == '!')
					return TOK_RM;
			}
				
			return TOK_COMMENT;
		}
		
		if (strncmp(IdentifierStr, "qwop", 4) == 0) {  //string starting with "qwop"
			if (IdentifierStr_len == 4)
				return TOK_OUTPUT;
			if (IdentifierStr_len == 5)
				switch (IdentifierStr[4]) {
					case '.': return TOK_INPUT;
					case '!': return TOK_JUMP_OPEN;
					case '?': return TOK_DECR;
					default: return TOK_JUMP_CLOSED;
				}
			return TOK_COMMENT;
		}
    }
    return TOK_EOF;
}
```

**Comment by LandonPowell** [comment]
Wonderful code, @Randl , but it seems tudurom has unfortunately closed this issue to save face, so the chance of anyone seeing or using it is low. Consider putting in a pull request. I'm sure Kenneth will merge.
